#https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html
# # with overline, for parts
# * with overline, for chapters
# =, for sections
# -, for subsections
# ^, for subsubsections
# ", for paragraphs

sectionchars = '*=-~"+`'

title = "m2rst config"

[project]
name = "md2rst"
description = "Customized post processing tool for broken links after pandoc conversion."
version = "1.0.0"
author = "m"

[markdown]
root_directory = '/home/user/qubes-translation-utilz/md2rst/refactor_test/TEST/markdown/qubesos.github.io.rtd'
redirect_base_url = 'https://foo.bar' # TODO
#excluded_files_from_redirect = ['README.md', 'CONTRIBUTING.md', 'hcl.md', 'downdloads.md']

[rst]
# TODO delete if we are going with just one directory
rst_directory = '/home/user/qubes-translation-utilz/md2rst/refactor_test/TEST/rst-convert/qubesos.github.io.rtd/_doc/'
copy_from_dir = '/home/user/qubes-translation-utilz/md2rst/preparation/'
md_file_names = ['admin-api-table.md', 'admin-api.md', 'doc.md']
rst_config_files = ['requirements.txt', 'conf.py', '.readthedocs.yaml']
rst_files = ['intro.rst']
skip_files = ['gui.rst']
directory_to_remove = 'external'
files_to_remove = [
    '.gitlab-ci.yml',
    '.travis.yml',
    'qubes-core-admin-client.rst',
    'qubes-core-admin.rst',
    'qubes-core-stack.rst',
    'system-doc.rst',
    'qubes-template-configs.rst',
    'community-recommended-hardware.rst']
# TODO hcl.rst downloads.rst etc the redirects
# either exclude them when converting or use redirects plugin.
#Better use redirects plugin with empty rst files that can be populated in a later stage
old_uri = ['/hcl', '/downloads']

[svg]
# should reside in the rst_directory or subdirectories
svg_files_to_png = ['admin-api-architecture.svg']
#replace_svg_with_png_in_rst_files = false
replace_svg_with_png_in_rst_files = true

[run]
md_map = true

#pypandoc = false
pypandoc = true
#copy_md_files = false
copy_md_files = true
#copy_rst_files = false
copy_rst_files = true
#remove_rst_directory = false
remove_rst_directory = true
#remove_rst_files = false
remove_rst_files = true

#docutils_validate = false
docutils_validate = true
#
#qubes_rst = false
qubes_rst = true

#svg_png_conversion_replacement = false
svg_png_conversion_replacement = true
#markdown_links_leftover = false
markdown_links_leftover = true

#redirect_markdown = true
redirect_markdown = false

#git reset --hard && find . ! -not -name 'README.md' -o ! -not -name 'CONTRIBUTING.md' -o -type f -name '*.rst' -delete


[url_mapping]
save_to_json = false
#save_to_json = true
dump_directory_name = '/home/user/qubes-translation-utilz/md2rst/refactor_test/md-dump/'
dump_external_filename = 'external_redirects_mappings.json'
dump_docs_filename = 'md_doc_permalinks_and_redirects_to_filepath_map.json'
dump_pages_filename = 'md_pages_permalinks_and_redirects_to_filepath_map.json'

[log]
# TODO it was just a string now it is a list !!!
patterns = ['architecture']
output = 'mapping.txt'
logfile = '/tmp/md2rst.log'

[test]
run = false
#run = true
docutils_validate = true



# DONE
# can be deleted, is referenced only via url in the index
#file_name = '/home/user/testingfilez/qubes-core-admin-client.rst'
# can be deleted, is referenced only via url in the index
#file_name = '/home/user/testingfilez/qubes-core-admin.rst'
# can be deleted, is referenced only via url in the index
#file_name = '/home/user/testingfilez/qubes-core-stack.rst'
# just  a redirect to index, developer documentation section, can be removed
#file_name = '/home/user/testingfilez/system-doc.rst'
# can be deleted, is referenced only via url in the index
#file_name = '/home/user/testingfilez/qubes-template-configs.rst'
# can be deleted, is referenced only via url in the index
#file_name = '/home/user/testingfilez/community-recommended-hardware.rst'

# TODO those who have no origin file in testingfilez dir -> have to be filled in or otherwise processed!


# wrap rst text? really? 80 characters per line? standard? why?

#file_name = '/home/user/testingfilez/admin-api.rst' # TODO

#https://gist.github.com/dbrgn/2922648
#file_name = '/home/user/testingfilez/4_1/release-notes.rst' # TODO
#file_name = '/home/user/testingfilez/4_1/schedule.rst' # TODO
#file_name = '/home/user/testingfilez/video-tours.rst' # TODO
#file_name = '/home/user/testingfilez/research.rst' # TODO
#file_name = '/home/user/testingfilez/hcl.rst' # TODO
#file_name = '/home/user/testingfilez/downloads.rst' # TODO
#file_name = '/home/user/testingfilez/intro.rst' # TODO
#file_name = '/home/user/testingfilez/index.rst' # TODO
#only one usability-ux has a reference to the /doc/visual style guide
file_name = '/home/user/testingfilez/visual-style-guide.rst' # TODO empty,

# TODO toctree example






