#https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html
# # with overline, for parts
# * with overline, for chapters
# =, for sections
# -, for subsections
# ^, for subsubsections
# ", for paragraphs

sectionchars = '*=-~"+`'

title = "m2rst config"

[project]
name = "md2rst"
description = "Customized post processing tool for broken links after pandoc conversion."
version = "1.0.0"
author = "m"

[markdown]
root_directory = '/home/user/qubes/convert/markdown/qubesos.github.io'
redirect_base_url = 'https://foo.bar' # TODO

[rst]
# TODO delete if we are going with just one directory
rst_directory = '/home/user/qubes/convert/rst-convert/qubesos.github.io/_doc/'

copy_from_dir = '/home/user/qubes/tools/qubes-translation-utilz/md2rst/resources/' # TODO WTF 
#copy_from_dir = '/home/user/qubes/md2rst/preparation/' # TODO WTF 
md_file_names = ['doc.md'] # TODO nice to have
# files that should remain in md, to be moved to qubesos.github.io repo
skip_md = ['user/downloading-installing-upgrading/downloads.md', 'user/hardware/hcl.md', 'introduction/intro.md', 'introduction/privacy.md', 'introduction/code-of-conduct.md', 'introdution/statistics.md', 'user/hardware/community-recommended-hardware.rst', 'developer/building/qubes-template-configs.rst', 'developer/general/visual-style-guide.rst']
rst_file_names = ['requirements.txt', 'conf.py', '.readthedocs.yaml', 'introduction/video-tours.rst', 'index.rst'] # TODO nice to have
directory_to_remove = 'external' # TODO nice to have
hidden_files_to_remove = ['.gitlab-ci.yml', '.travis.yml'] # TODO nice to have

[svg]
# should reside in the rst_directory or subdirectories
svg_files_to_png = ['admin-api-architecture.svg']
#replace_svg_with_png_in_rst_files = false
replace_svg_with_png_in_rst_files = true

[run]
md_map = true

#pypandoc = false
pypandoc = true
#copy_md_files = false
copy_md_files = true
#copy_rst_files = false
copy_rst_files = true
#remove_rst_directory = false
remove_rst_directory = true
#remove_hidden_files = false
remove_hidden_files = true

docutils_validate = false
#docutils_validate = true
#

sphinx_refs = true
# no sphinx-build but sphinx-autobuild which does watch and does  not end itself TODO
#sphinx_refs = false

qubes_rst = false
#qubes_rst = true

svg_png_conversion_replacement = false
#svg_png_conversion_replacement = true
markdown_links_leftover = false # TODO
#markdown_links_leftover = true # TODO
redirect_markdown = false # TODO

#git reset --hard && find . ! -not -name 'README.md' -o ! -not -name 'CONTRIBUTING.md' -o -type f -name '*.rst' -delete


[url_mapping]
#save_to_json = false
save_to_json = true
dump_directory_name = '/home/user/qubes/convert/md-dump/'
dump_external_filename = 'external_redirects_mappings.json'
dump_docs_filename = 'md_doc_permalinks_and_redirects_to_filepath_map.json'
dump_pages_filename = 'md_pages_permalinks_and_redirects_to_filepath_map.json'
dump_localrefs_filename = 'internal_refs.json'

[log]
# TODO it was just a string now it is a list !!!
patterns = ['architecture']
output = 'mapping.txt'
logfile = '/tmp/md2rst.log'

[test]
run = false
#run = true

#validate = true
validate = false

#file_name = '/home/user/testingfilez/qubes-template-configs.rst' # TODO empty?
#file_name = '/home/user/testingfilez/source-code.rst'
#file_name = '/home/user/testingfilez/coding-style.rst'
#file_name = '/home/user/testingfilez/code-signing.rst'

#file_name = '/home/user/testingfilez/gsoc.rst'
#file_name = '/home/user/testingfilez/license.rst' # OK
#file_name = '/home/user/testingfilez/development-workflow.rst'
#file_name = '/home/user/testingfilez/qubes-builder-details.rst' # OK
#file_name = '/home/user/testingfilez/qubes-iso-building.rst'
#file_name = '/home/user/testingfilez/qubes-builder.rst' # TODO debug
#< SYSTEM MESSAGE  for: /home/user/testingfilez/qubes-builder.rst:3: (INFO/1) Enumerated list start value not ordinal-1: "3" (ordinal 3)


# DONE


[manual]




