#https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html
# # with overline, for parts
# * with overline, for chapters
# =, for sections
# -, for subsections
# ^, for subsubsections
# ", for paragraphs

sectionchars = '*=-~"+`'

title = "m2rst config"

[project]
name = "md2rst"
description = "Customized post processing tool for broken links after pandoc conversion."
version = "1.0.0"
author = "m"

[log]
logfile = '/tmp/md2rst.log'

[markdown]
root_directory = '/home/user/qubes-translation-utilz/md2rst/refactor_test/TEST/markdown/qubesos.github.io.rtd'
redirect_base_url = 'https://foo.bar' # TODO

[rst]
rst_directory = '/home/user/qubes-translation-utilz/md2rst/refactor_test/TEST/rst-convert-monster-merge/qubes-rst/'
copy_from_dir = '/home/user/qubes-translation-utilz/md2rst/preparation/'
md_file_names = ['doc.md']
rst_config_files = ['requirements.txt', 'conf.py', '.readthedocs.yaml']
rst_files = ['research.rst', 'intro.rst', 'admin-api.rst']
skip_files = ['gui.rst', 'research.rst', 'intro.rst', 'admin-api.rst']
directories_to_remove = ['external']
files_to_remove = [
    '.git',
    '.gitlab-ci.yml',
    '.travis.yml',
    'qubes-core-admin-client.rst',
    'qubes-core-admin.rst',
    'qubes-core-stack.rst',
    'system-doc.rst',
    'qubes-template-configs.rst',
    'community-recommended-hardware.rst']

[git]
# expects signed commits preconfigured
# performs ONLY initial commit after pandoc conversion and rst cross linkings,
# as well as adding the attachment repo as sumodule
origin_url = 'https://github.com/maiska/qubes-rst.git'
attachment_url = 'https://github.com/maiska/qubes-attachment.rtd.git'

[svg]
svg_files_to_png = ['admin-api-architecture.svg', 'u2f.svg', 'update_table-20140424-170010.svg', 'release-cycle.svg']

[run]

md_map = true

#####################
# 1-st stage all true
#####################
pypandoc = true
#pypandoc = false
#copy_md_files = false
copy_md_files = true
#copy_rst_files = false
copy_rst_files = true
#remove_rst_directory = false
remove_rst_directory = true
#remove_rst_files = false
remove_rst_files = true

####################
# 2nd stage all true
####################
docutils_validate = false
#docutils_validate = true
qubes_rst = false
#qubes_rst = true
git_init = false
#git_init = true
svg_png_conversion_replacement = false
#svg_png_conversion_replacement = true
markdown_links_leftover = false
#markdown_links_leftover = true
replace_custom_strings = false
#replace_custom_strings = true

###########
# TODO test for bugs
# 3rd stage
###########
redirect_markdown = false
#redirect_markdown = true

[replace_custom_strings_values]
'user/how-to-guides/how-to-copy-from-dom0:copying from dom0' = 'user/how-to-guides/how-to-copy-from-dom0:copying **from** dom0'
'<introduction/faq:general  security>' = '<introduction/faq:general \& security>'
'/doc/glossary:vm' = 'user/reference/glossary:vm'
'</user/reference/glossary:app qube>' = '<user/reference/glossary:app qube>'
'developer/services/qrexec-internals:qrexec policy implementation' = 'developer/services/qrexec-internals:\`\`qrexec-policy\`\` implementation'
'user/how-to-guides/how-to-use-pci-devices:qvm-pci usage' = 'user/how-to-guides/how-to-use-pci-devices:\`\`qvm-pci\`\` usage'
'user/advanced-topics/salt:update.qubes-dom0' = 'user/advanced-topics/salt:\`\`update.qubes-dom0\`\`'
'user/advanced-topics/salt:update.qubes-vm' = 'user/advanced-topics/salt:\`\`update.qubes-vm\`\`'
'```openqa_investigator`` <' = '`openqa_investigator <'
':ref:`ISO downloads <user/downloading-installing-upgrading/downloads:mirrors>`' = '`ISO downloads <https://www.qubes-os.org/downloads/#mirrors>__'
':ref:`here <user/downloading-installing-upgrading/downloads:mirrors>`' = '`here <https://www.qubes-os.org/downloads/#mirrors>__'
':ref:`download mirrors <user/downloading-installing-upgrading/downloads:mirrors>`' = '`download mirrors <https://www.qubes-os.org/downloads/#mirrors>__'
':doc:`Qubes News RSS feed <https://www.qubes-os.org/feed.xml>`' = '`Qubes News RSS feed <https://www.qubes-os.org/feed.xml>`'

[test]
run = false
#run = true
docutils_validate = true
#file_name = '/home/user/testingfilez/automated-tests.rst'

# notes
# strikethrough for rst https://sphinx.silverrainz.me/strike/ and in conf.py
# https://github.com/sphinx-notes/strike

#https://gist.github.com/dbrgn/2922648










